exports.HANDLE_REQUEST_DONE = 'HANDLE_REQUEST_DONE';
exports.ADD_SCORE = 'ADD_SCORE';
exports.SET_LIVE_SCORE = 'SET_LIVE_SCORE';
exports.SET_LIVE_USER = 'SET_LIVE_USER';
exports.REQUEST_DATA = 'REQUEST_DATA';
exports.RECIEVE_DATA = 'RECIEVE_DATA';
exports.SORT_BY_SCORE_DESC = 'SORT_BY_SCORE_DESC';
exports.SORT_BY_SCORE_ASC = 'SORT_BY_SCORE_ASC';
exports.SORT_BY_USER_DESC = 'SORT_BY_USER_DESC';
exports.SORT_BY_USER_ASC = 'SORT_BY_USER_ASC';

